// <auto-generated />
using System;
using Infinia.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infinia.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240917100029_DroppedFamilyMembersCount")]
    partial class DroppedFamilyMembersCount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Account identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Account balance");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Branch that the country is associated with");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Account creation date");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("customer account identifier");

                    b.Property<byte[]>("EncryptedIBAN")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Account number");

                    b.Property<DateTime?>("LastMonthlyFeeDeduction")
                        .HasColumnType("datetime2")
                        .HasComment("Last time a monthly fee was deducted");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Account monthly fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Account name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Account status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Account type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");

                    b.HasComment("Account entity");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Balance = 1000m,
                            Branch = "Sliven",
                            CreationDate = new DateTime(2024, 9, 17, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6163),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 37, 24, 39, 194, 187, 85, 25, 67, 195, 56, 247, 137, 17, 220, 32, 81, 144, 82, 184, 28, 19, 253, 96, 177, 255, 107, 24, 58, 20, 70, 223, 151, 177, 120, 40, 127, 208, 127, 249, 54, 75, 220, 180, 194, 3, 193, 139, 189 },
                            MonthlyFee = 2m,
                            Name = "Current acount",
                            Status = "Open",
                            Type = "Current"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 200m,
                            Branch = "Sliven",
                            CreationDate = new DateTime(2024, 9, 17, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6163),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 37, 24, 39, 194, 187, 85, 25, 67, 195, 56, 247, 137, 17, 220, 32, 81, 144, 82, 184, 28, 19, 253, 96, 177, 255, 107, 24, 58, 20, 70, 223, 151, 177, 120, 40, 127, 208, 127, 249, 54, 75, 220, 180, 194, 3, 193, 139, 189 },
                            MonthlyFee = 2m,
                            Name = "Savings account",
                            Status = "Open",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 900m,
                            Branch = "Sliven",
                            CreationDate = new DateTime(2024, 8, 28, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6240),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 193, 10, 140, 103, 113, 25, 240, 73, 189, 131, 84, 240, 133, 51, 134, 120, 251, 105, 160, 55, 185, 161, 253, 175, 31, 209, 58, 112, 169, 238, 137, 250, 196, 39, 48, 190, 187, 42, 71, 23, 125, 144, 117, 50, 69, 224, 12, 122 },
                            MonthlyFee = 2m,
                            Name = "Current acount-2",
                            Status = "Open",
                            Type = "Current"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 0m,
                            Branch = "None",
                            CreationDate = new DateTime(2024, 8, 18, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6261),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 31, 206, 109, 135, 141, 71, 209, 126, 42, 101, 231, 236, 67, 171, 245, 18, 100, 92, 210, 218, 76, 159, 101, 79, 14, 131, 4, 157, 91, 180, 162, 152, 128, 221, 107, 227, 194, 167, 126, 176, 76, 155, 164, 21, 230, 73, 221, 13 },
                            MonthlyFee = 0m,
                            Name = "Savings account for bank account",
                            Status = "Open",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = 1,
                            Balance = 100000000m,
                            Branch = "None",
                            CreationDate = new DateTime(2024, 8, 18, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6261),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 31, 206, 109, 135, 141, 71, 209, 126, 42, 101, 231, 236, 67, 171, 245, 18, 100, 92, 210, 218, 76, 159, 101, 79, 14, 131, 4, 157, 91, 180, 162, 152, 128, 221, 107, 227, 194, 167, 126, 176, 76, 155, 164, 21, 230, 73, 221, 13 },
                            MonthlyFee = 0m,
                            Name = "Bank account",
                            Status = "Open",
                            Type = "Bank"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 100m,
                            Branch = "Sliven",
                            CreationDate = new DateTime(2024, 8, 28, 13, 0, 29, 211, DateTimeKind.Local).AddTicks(6240),
                            CustomerId = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            EncryptedIBAN = new byte[] { 193, 10, 140, 103, 113, 25, 240, 73, 189, 131, 84, 240, 133, 51, 134, 120, 251, 105, 160, 55, 185, 161, 253, 175, 31, 209, 58, 112, 169, 238, 137, 250, 196, 39, 48, 190, 187, 42, 71, 23, 125, 144, 117, 50, 69, 224, 12, 122 },
                            MonthlyFee = 2m,
                            Name = "Savings account-2",
                            Status = "Open",
                            Type = "Savings"
                        });
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Address identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("City name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Country name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Postal or zip code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Street address, including house number");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasComment("Address entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sliven",
                            Country = "Bulgaria",
                            PostalCode = "8800",
                            Street = "Sini kamani 28"
                        });
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasComment("Customer address identifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdentityCardId")
                        .HasColumnType("int")
                        .HasComment("Customer identity card identifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Customer name from identity card");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("IdentityCardId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Customer entity");

                    b.HasData(
                        new
                        {
                            Id = "2cbfb88d - c6a3 - 445e-a0f3 - 2492fbbbc137",
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "9082b0f9-846a-4768-9112-0caa663c8853",
                            Email = "ivanivanov@gmail.com",
                            EmailConfirmed = true,
                            IdentityCardId = 1,
                            LockoutEnabled = false,
                            Name = "Ivan Ivanov",
                            NormalizedEmail = "IVANIBANOV@GMAIL.COM",
                            NormalizedUserName = "IVANIVANOV",
                            PasswordHash = "AQAAAAEAACcQAAAAEKAHInML8nXOC7sDoCZjlLNrTqVOq5F7EATT60QyNbkLob39XlrMM9Re7LxDyMBcTQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cad15a37-923b-4abc-9758-f1ff152a4682",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov"
                        });
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Education identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Education level");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasComment("Education entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.EmployerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Employer information identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Employer name");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit")
                        .HasComment("Is the person retired");

                    b.Property<int>("MonthsAtJob")
                        .HasColumnType("int")
                        .HasComment("Months at job");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Position");

                    b.Property<int>("TotalWorkExperienceMonths")
                        .HasColumnType("int")
                        .HasComment("Total work experience months");

                    b.Property<int>("TotalWorkExperienceYears")
                        .HasColumnType("int")
                        .HasComment("Total work experience years");

                    b.Property<int>("YearsAtJob")
                        .HasColumnType("int")
                        .HasComment("Years at job");

                    b.HasKey("Id");

                    b.ToTable("EmployerInfos");

                    b.HasComment("Employer information entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.HouselholdInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Household information identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Dependents")
                        .HasColumnType("int")
                        .HasComment("Number of dependents that depend on the income of the applicant");

                    b.Property<int>("MembersWithProvenIncome")
                        .HasColumnType("int")
                        .HasComment("Number of household members with proven income");

                    b.Property<int>("NumberOfHouseholdMembers")
                        .HasColumnType("int")
                        .HasComment("Number of household members");

                    b.HasKey("Id");

                    b.ToTable("HouselholdInfos");

                    b.HasComment("Household information entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.IdentityCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identity card identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("EncryptedCardNumber")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card number");

                    b.Property<byte[]>("EncryptedDateOfIssue")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card date of issue");

                    b.Property<byte[]>("EncryptedIssuer")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card issuer");

                    b.Property<byte[]>("EncryptedNationality")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card nationality");

                    b.Property<byte[]>("EncryptedSSN")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card SSN");

                    b.Property<byte[]>("EncryptedSex")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Identity card sex");

                    b.HasKey("Id");

                    b.ToTable("IdentityCards");

                    b.HasComment("Identity card entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EncryptedCardNumber = new byte[] { 49, 34, 67, 29, 133, 160, 202, 196, 145, 181, 192, 114, 229, 113, 58, 22, 193, 50, 4, 2, 210, 21, 75, 154, 140, 102, 163, 28, 86, 92, 151, 73 },
                            EncryptedDateOfIssue = new byte[] { 179, 85, 117, 239, 66, 92, 60, 97, 70, 3, 196, 223, 92, 112, 85, 69, 175, 173, 235, 42, 60, 70, 176, 166, 214, 41, 252, 156, 139, 109, 140, 130 },
                            EncryptedIssuer = new byte[] { 158, 114, 169, 139, 148, 7, 21, 70, 47, 14, 123, 36, 201, 172, 203, 230, 58, 200, 67, 15, 127, 249, 232, 154, 203, 237, 132, 80, 47, 222, 90, 250 },
                            EncryptedNationality = new byte[] { 134, 55, 67, 164, 48, 44, 210, 254, 78, 218, 227, 4, 6, 97, 152, 180, 234, 106, 141, 247, 74, 13, 39, 26, 219, 173, 161, 238, 61, 183, 169, 221 },
                            EncryptedSSN = new byte[] { 172, 50, 196, 250, 62, 125, 215, 96, 161, 1, 179, 55, 24, 130, 67, 36, 74, 62, 252, 121, 145, 155, 210, 128, 107, 87, 3, 72, 57, 56, 119, 247 },
                            EncryptedSex = new byte[] { 233, 27, 160, 30, 61, 187, 236, 11, 178, 98, 13, 55, 198, 108, 31, 34, 127, 147, 107, 103, 173, 182, 81, 243, 24, 43, 202, 53, 95, 182, 23, 9 }
                        });
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.IncomeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Income information identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BusinessIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Business income");

                    b.Property<decimal>("CivilContractIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Civil contract income");

                    b.Property<decimal>("FixedMonthlyExpenses")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Fixed monthly expenses");

                    b.Property<decimal>("FreelanceIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Freelance income");

                    b.Property<bool>("HasOtherCredits")
                        .HasColumnType("bit")
                        .HasComment("Has other credits");

                    b.Property<decimal>("NetMonthlyIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Net monthly income");

                    b.Property<decimal>("OtherIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Other income");

                    b.Property<decimal>("PensionIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Pension income");

                    b.Property<decimal>("PermanentContractIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Permanent contract income");

                    b.Property<decimal>("TemporaryContractIncome")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Temporary contract income");

                    b.HasKey("Id");

                    b.ToTable("IncomeInfos");

                    b.HasComment("Income information entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Loan application identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasComment("Loan application account identifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Loan application date");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Loan application customer identifier");

                    b.Property<int>("EducationId")
                        .HasColumnType("int")
                        .HasComment("Education identifier");

                    b.Property<int>("EmployerInfoId")
                        .HasColumnType("int")
                        .HasComment("Employer information identifier");

                    b.Property<int>("HouseholdInfoId")
                        .HasColumnType("int")
                        .HasComment("Household information identifier");

                    b.Property<int>("IncomeInfoId")
                        .HasColumnType("int")
                        .HasComment("Income information identifier");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasComment("Interest rate");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Loan amount");

                    b.Property<int>("LoanTermMonths")
                        .HasColumnType("int")
                        .HasComment("Loan term in months");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int")
                        .HasComment("Marital status identifier");

                    b.Property<int>("PropertyStatusId")
                        .HasColumnType("int")
                        .HasComment("Property status identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Loan application status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EducationId");

                    b.HasIndex("EmployerInfoId");

                    b.HasIndex("HouseholdInfoId");

                    b.HasIndex("IncomeInfoId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("PropertyStatusId");

                    b.ToTable("LoanApplications");

                    b.HasComment("Loan application entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Marital status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Marital status");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");

                    b.HasComment("Marital status entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Notification identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Notification message");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Notification creation date");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Customer notification identifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasComment("Notification status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Notifications");

                    b.HasComment("Notification entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.PropertyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Property status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("HasApartmentOrHouse")
                        .HasColumnType("bit")
                        .HasComment("Has apartment or house");

                    b.Property<bool>("HasCommercialProperty")
                        .HasColumnType("bit")
                        .HasComment("Has commercial property");

                    b.Property<bool>("HasLand")
                        .HasColumnType("bit")
                        .HasComment("Has land");

                    b.Property<bool>("HasMultipleProperties")
                        .HasColumnType("bit")
                        .HasComment("Has multiple properties");

                    b.Property<bool>("HasPartialOwnership")
                        .HasColumnType("bit")
                        .HasComment("Has partial ownership");

                    b.Property<int>("MonthsInResidence")
                        .HasColumnType("int")
                        .HasComment("Months in residence");

                    b.Property<bool>("NoProperty")
                        .HasColumnType("bit")
                        .HasComment("No property");

                    b.Property<string>("ResidenceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Residence status");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("int")
                        .HasComment("Vehicle count");

                    b.Property<int>("YearsInResidence")
                        .HasColumnType("int")
                        .HasComment("Years in residence");

                    b.HasKey("Id");

                    b.ToTable("PropertyStatuses");

                    b.HasComment("Property status entity");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Transaction identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasComment("Transaction account identifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Transaction amount");

                    b.Property<string>("Bic")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Transaction BIC");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Transaction description");

                    b.Property<byte[]>("EncryptedReceiverIBAN")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("IBAN of the receiver");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Transaction fee");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Transaction reason");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Full name of the receiver of the transaction");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasComment("Transaction date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Transaction type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasComment("Transaction entity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Account", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Customer", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.IdentityCard", "IdentityCard")
                        .WithOne()
                        .HasForeignKey("Infinia.Infrastructure.Data.DataModels.Customer", "IdentityCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("IdentityCard");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.LoanApplication", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.EmployerInfo", "EmployerInfo")
                        .WithMany()
                        .HasForeignKey("EmployerInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.HouselholdInfo", "HouseholdInfo")
                        .WithMany()
                        .HasForeignKey("HouseholdInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.IncomeInfo", "IncomeInfo")
                        .WithMany()
                        .HasForeignKey("IncomeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.PropertyStatus", "PropertyStatus")
                        .WithMany()
                        .HasForeignKey("PropertyStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");

                    b.Navigation("Education");

                    b.Navigation("EmployerInfo");

                    b.Navigation("HouseholdInfo");

                    b.Navigation("IncomeInfo");

                    b.Navigation("MaritalStatus");

                    b.Navigation("PropertyStatus");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Notification", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Transaction", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infinia.Infrastructure.Data.DataModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Address", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Infinia.Infrastructure.Data.DataModels.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("LoanApplications");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
